swagger: '2.0'
info:
  title: Shopping Cart API
  description: Add and delete products from a Shopping Cart
  version: "1.0.0"
# the domain of the service
host: api.shopping-cart.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /products:
    get:
      summary: Get the list of added products
      description: |
        The Products endpoint returns information about the products added to the cart.
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add a product to the Shopping Cart
      description: |
        The Products endpoint adds a product to the shopping cart.
      parameters:
        - name: id
          in: query
          description: Product's id.
          required: true
          type: integer
          format: simple
        - name: name
          in: query
          description: Product's name.
          required: true
          type: string
          format: simple
        - name: price
          in: query
          description: Product's price.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            post:
    delete:        
      summary: Delete a product to the Shopping Cart
      description: |
        The Products endpoint returns removes a product from the Shopping cart.
      parameters:
        - name: id
          in: query
          description: Product's id.
          required: true
          type: integer
          format: simple
        - name: name
          in: query
          description: Product's name.
          required: true
          type: string
          format: simple
        - name: price
          in: query
          description: Product's price.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific product.
      name:
        type: string
        description: Display name of product.
      price:
        type: number
        description: Price of product. 
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
